enum LocalDataFieldType {
  STRING_LIST,
  STRING,
  INT,
  DOUBLE,
  BOOL,
}

enum LocalDataFieldName {
  USER_PROFILE,
  USER_ROLE,
  USER_TOKEN,
  USER_TOKEN_EXPIRED_DATETIME,
  USER_TOKEN_EXPIRED_DATETIMEV2,
  LAON_SCHEDULE_OFFLINE,
  LOAN_COLLECTION_SUBMIT,
  SAVE_LOGIN_DATE,
}
